//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPGeek.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class park
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public park()
        {
            this.survey_result = new HashSet<survey_result>();
            this.weathers = new HashSet<weather>();
        }
    
        public string parkCode { get; set; }
        public string parkName { get; set; }
        public string state { get; set; }
        public int acreage { get; set; }
        public int elevationInFeet { get; set; }
        public float milesOfTrail { get; set; }
        public int numberOfCampsites { get; set; }
        public string climate { get; set; }
        public int yearFounded { get; set; }
        public int annualVisitorCount { get; set; }
        public string inspirationalQuote { get; set; }
        public string inspirationalQuoteSource { get; set; }
        public string parkDescription { get; set; }
        public int entryFee { get; set; }
        public int numberOfAnimalSpecies { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<survey_result> survey_result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<weather> weathers { get; set; }
    }
}
