//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPGeek.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class weather
    {
        public string parkCode { get; set; }
        public int fiveDayForecastValue { get; set; }
        public int low { get; set; }
        public int high { get; set; }
        public string forecast { get; set; }
    
        public virtual park park { get; set; }
    }
}
